### ISSUE TITLE
Footer Update (Enhancing the functionality)

### ISSUE THREAD

**Issue by rikhiltaneja** [kalviumcommunity/S53_Aayush_Capstone_InterPrep#30]
Currently the footer of this project is very simple and kind of non-functional. This is not good for providing the best User Experience as Footer should contain some necessary nagivation options and details about the website. I will use ChakraUI itself to enhance the looks as well as the functionality of the Footer leading to a better UX of the website.

**Comment by aayushwrld** [comment]
Great, you can start working on this.

**Comment by aayushwrld** [comment]
Issue resolved, [PR Link 31](https://github.com/kalviumcommunity/S53_Aayush_Capstone_InterPrep/pull/31)
